### ISSUE TITLE
The badges plugin causes a "twitch" effect to the profile popover

### ISSUE THREAD

**Issue by mickmister** [larkox/mattermost-plugin-badges#6]
Similar to https://github.com/larkox/mattermost-plugin-badges/issues/4, the badges plugin causes a bit of a "twitch" by expanding or collapsing after the badges are loaded, depending on if the user has badges or not. This is especially apparent when the user's profile is opened more than once, as I would expect the badges to have already loaded before opening the popover.

I'm thinking we can have a caching period where we store the user's badges in redux so the twitch effect only occurs on the first opening of the popover. We can still fetch them on open to show up-to-date data, but showing the cached badges in the meantime avoids this effect of twitching. This is how the user attributes plugin avoids this effect on subsequent openings of the popover. @larkox What do you think?

**Comment by larkox** [comment]
LGTM. Right now is "reserving enough space" in order to get properly positioned.

My worry is that if we have only one line of badges, and we get a new one, it will grow and then it may overflow from the screen. But probably is a rare enough case to prefer removing the twitch.

**Comment by mickmister** [comment]
@larkox As this plugin is gaining traction from customers, I think this issue will be more prevalent. What are your thoughts on this issue, maybe get the community involved somehow?

**Comment by mickmister** [comment]
Just a thought, we should make sure the `Loading...` text matches the height of the badge images, and enforce a `max-height` for badges that matches this. I think this would resolve the twitching for users with one row of badges

**Comment by sinansonmez** [comment]
> Just a thought, we should make sure the `Loading...` text matches the height of the badge images, and enforce a `max-height` for badges that matches this. I think this would resolve the twitching for users with one row of badges

https://github.com/larkox/mattermost-plugin-badges/blob/8d93d8ca5d1e8b98e0e84eec1c50515d07eb478b/webapp/src/components/user_popover/badge_list.tsx#L157-L158

@mickmister @larkox yeah, that could be part of the solution. Because, currently, as seen below height of loading is set to cover two rows. My proposal would be:
- make sure the `Loading...` text matches the height of badge images
- by default show only one row. If it requires more than 1 row, show them with show more button at the end of the row

**Comment by larkox** [comment]
This approach is because we reserve "as much space as we will need when we have all the information". The reasoning behind that is that growing the user profile gives more problems (stuff outside of the visible area) than shrinking.

If we go this direction, we will never show 2 lines of images, just one. I am ok with that, but... We won't show the "and more" link always neither. So there will be a small twitch there when we reserve space for the "and more" link and the "and more" link never appears.

Not saying this shouldn't be done, just saying that any solution has its problems with the current implementation of the user profile in the webapp.

**Comment by sinansonmez** [comment]
Thanks for the feedback @larkox 

I was thinking that we reserve a space for only one row. This row would consist `badges` and `and more` icon button. Therefore there shouldnt be any twitch even if we dont show `and more` button. If there is less badge, we only show those badges.

It is not clear to me what do you mean by `growing the user profile gives more problems (stuff outside of the visible area) than shrinking`. If you can elaborate I can try to address them as I recently gave UI update to profile `popover`

**Comment by sinansonmez** [comment]
here is a quick demo of my idea. 

Based on number of badges, we should also reserve some space for width as well. After that we can prevent twitch effect vertically and horizontally

https://user-images.githubusercontent.com/37421564/214153411-7c776f72-024d-4f3c-9de4-026ef4bea251.mov

**Comment by sinansonmez** [comment]
> That should work.

@larkox I will proceed by opening a PR for the change

> The button to send a direct message to this user is below the border of the screen, so it is not clickable.

Ah, now I see your point. This should be addressed in profile popover. If you can create a ticket for that, I can follow up. Otherwise I can ask someone to create a ticket
